# This is a workflow which will delete the ephemeral environment for ActiveState Developers

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    types: [ closed ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a multiples job under "build"
  build:

   # The type of runner that the job will run on
    runs-on: ubuntu-latest

    #Deletes the sanity test bucket
    steps:
      - name: Upload to S3
        run: aws s3 rb s3://testbucket2022103
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
    #Deletes the lambda function stack
      - name: Delete the lambda function stack
        run: aws cloudformation delete-stack --stack-name lambda2 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
    #Remove the final.yaml script    
      - name: Remove the final.yaml script
        run: aws s3 rm s3://activestatebucket/final.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
    # Deletes each and every single last services present in the environment along with RDS     
      - name: Delete the final ephimeral stack
        run: aws cloudformation delete-stack --stack-name activestateephimeral 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          
          
          